dataset:
  class: HER2
  path: ./data/aff_optim_1n8z_0328
  node_feature: residue_symbol
  residue_feature: default
  split:
    test_set: 1n8z_renum.pdb_HL_C

task:
  class: BindingAffinityChange
  model:
    class: DDGPredictor
    hidden_dim: 128
    pair_dim: 64
    max_relpos: 32
    num_layers: 2
  normalization: False
  task: [ddG]
  criterion: mse
  metric: ["mae", "rmse", "spearmanr", "pearsonr"]

optimizer:
  class: Adam
  lr: 1.0e-4

engine:
  gpus: [0]
  batch_size: 8

checkpoints:
  - ./checkpoints/bindddg0.pth
  - ./checkpoints/bindddg1.pth
  - ./checkpoints/bindddg2.pth
  - ./checkpoints/bindddg3.pth
  - ./checkpoints/bindddg4.pth
